### ISSUE TITLE
bytebuffer have problem on next.js

### ISSUE THREAD

**Issue by piyanggoon** [DoctorMcKay/node-websocket13#4]
Module not found: Can't resolve 'memcpy' in 'xxx/node_modules/bytebuffer/dist'

Import trace for requested module:
./node_modules/bytebuffer/dist/bytebuffer-node.js
./node_modules/websocket13/dist/streams/StreamedOutgoingMessage.js
./node_modules/websocket13/dist/index.js
./node_modules/steam-session/dist/transports/WebSocketCMTransport.js
./node_modules/steam-session/dist/LoginSession.js
./node_modules/steam-session/dist/index.js
./node_modules/steamcommunity/components/login.js
./node_modules/steamcommunity/index.js
./src/app/api/steam/tradeurl/route.ts

**Comment by piyanggoon** [comment]
problem is bytebuffer use memcpy i try npm install by external project still build fail, i try set memcpy = null and link all package-lock.json to my own file it can compile without error.

**Comment by DoctorMcKay** [comment]
websocket13 does not work in the browser. Use the regular WebSocket constructor.
