### ISSUE TITLE
bun support

### ISSUE THREAD

**Issue by JeremyEspresso** [DoctorMcKay/node-websocket13#6]
Hi there, I've been trying to get this library to work on the "bun" runtime (https://bun.sh/), I am trying to use your steam libraries on the runtime but they seem to not work properly.

This is the error I am getting: 
```
{"level":"debug","message":"[W1] WebSocket disconnected with error: ERR_TLS_CERT_ALTNAME_INVALID fetching \"https://ext2-lhr1.steamserver.net:27023/cmsocket/\". For more information, pass `verbose: true` in the second argument to fetch()"}
```
Let me know if you need more information!

**Comment by DoctorMcKay** [comment]
Sorry, this is specifically a Node.js module. I can't help with runtimes that pretend to be Node-compatible but actually aren't.
